"""Add flavor column to ML Model

Revision ID: 319fc86b7f72
Revises: 395aff469925
Create Date: 2018-11-06 15:31:35.600670

"""

# revision identifiers, used by Alembic.
revision = '319fc86b7f72'
down_revision = '395aff469925'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deployed_on', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('flavor_id', sa.String(length=255), nullable=False))
        batch_op.drop_column('deployed')

    # ### end Alembic commands ###
